### ISSUE TITLE
Add MAC address and license setting to Booster

### ISSUE THREAD

**Issue by bergtwvd** [hlacontainers/pitch-booster#1]
Similar as with the Pitch CRC:
- add command line option `-m` and `-x`
- add ENVs (BOOSTER_LICENSE, BOOSTER_MACADDRESS, etc)
- add logic to handle this
- update documentation and examples

**Comment by martinffi** [comment]
New environment variables have been added, tested and seem to be working. Documentaiton is updated. I forgot to add command line variables -m and -x, I should do this later

**Comment by bergtwvd** [comment]
Command line options are needed since I use them in my CI/CD chain.

**Comment by martinffi** [comment]
The command line options -m and -x have been added. -m will override the MAC address, while -x while make the container stop before Booster is started. -m and -l can be used in conjunction, or the license string can be given via environment variable. However, if -l is used, the container will stop after activating the license, regardless of whether the -x option was given or not.
